name: Check admin teams and members in all repositories

on:
  workflow_dispatch:

jobs:
  check-admin-access-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub python-dotenv

      - name: Run repo-admin-check.py script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          ORG: ${{ vars.ORGANIZATION }}
        run: |
          python3 repo-admin-check.py > markdown_table.txt

      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { context, github } = require('@actions/github');
            const fs = require('fs');

            // Read the contents of markdown_table.txt
            const markdownTable = fs.readFileSync('markdown_table.txt', 'utf8');
            
            const issueTitle = "Admin Roles in Repositories";
            const issueBody = `### Admin Role Report\n\n${markdownTable}`;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody
            });
