name: Bulk Manage GitHub Secrets and Variables

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Target repository name'
        required: true
      secrets_json:
        description: 'JSON object of secrets to add'
        required: false
      variables_json:
        description: 'JSON object of variables to add'
        required: false

jobs:
  manage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install cryptography
        run: pip install cryptography

      - name: Run secret/variable manager
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          ORG: ${{ github.ORG }}
          REPO: ${{ github.event.inputs.repo_name }}
          SECRETS_JSON: ${{ github.event.inputs.secrets_json }}
          VARIABLES_JSON: ${{ github.event.inputs.variables_json }}
        run: python manage_github_actions_data.py
