name: stale repo identifier

on:
  workflow_dispatch:
  schedule:
    - cron: "3 2 1 * *"

permissions:
  contents: read
  issues: write

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Run stale_repos tool
        uses: github/stale-repos@v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ORGANIZATION: ${{ vars.ORGANIZATION }}
          EXEMPT_TOPICS: "keep,template"
          INACTIVE_DAYS: 55
          ACTIVITY_METHOD: "pushed"
          ADDITIONAL_METRICS: "release,pr"

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Stale repository report
          content-filepath: ./stale_repos.md
          assignees: JatinRautela14

      - name: Archive stale repos
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Parsing stale_repos.md to find repos..."
          grep -o 'https://github.com/[^[:space:]]*' stale_repos.md | sed 's#https://github.com/##' > repos.txt || true

          if [ ! -s repos.txt ]; then
            echo "No repositories found to archive. Exiting step."
            exit 0
          fi

          while IFS= read -r repo
          do
            echo "Archiving $repo"
            curl -s -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token $GH_TOKEN" \
              "https://api.github.com/repos/$repo" \
              -d '{"archived":true}'
          done < repos.txt

